site_name: Kirilll Blog
site_url: https://example.com/
nav:
    - Home: index.md
    - About: about.md
    - Установочные пакеты: pip.md
    - GitHub: github.md
    - Setting: setting.md
    - Creator space: dev.md
    - Blog: blog/models.md
theme: 
  name: material

dev_addr: 127.0.0.1:8026

site_author: Kirill Galachuk

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - toc:
        permalink: True

#сворачивание страницы 
collapse_single_pages: True

plugins:
    - search
    - awesome-pages
